ALTER FUNCTION [dbo].[AUTO_MaGiaoVien]()
RETURNS VARCHAR(6)
AS
BEGIN
	DECLARE @ID VARCHAR(6)
	IF (SELECT COUNT(MaGiaoVien) FROM GIAOVIEN) = 0
		SET @ID = '0'
	ELSE
		SELECT @ID = MAX(RIGHT(MaGiaoVien, 2)) FROM GIAOVIEN
		SELECT @ID = CASE
			WHEN @ID >= 0 and @ID < 9 THEN 'GV000' + CONVERT(CHAR, CONVERT(INT, @ID) + 1)
			WHEN @ID >= 9 THEN 'GV00' + CONVERT(CHAR, CONVERT(INT, @ID) + 1)
		END
	RETURN @ID
END
GO

ALTER FUNCTION [dbo].[AUTO_MaHocSinh]()
RETURNS VARCHAR(6)
AS
BEGIN
	DECLARE @ID VARCHAR(6)
	IF (SELECT COUNT(MaHocSinh) FROM HOCSINH) = 0
		SET @ID = '0'
	ELSE
		SELECT @ID = MAX(RIGHT(MaHocSinh, 2)) FROM HOCSINH
		SELECT @ID = CASE
			WHEN @ID >= 0 and @ID < 9 THEN 'HS000' + CONVERT(CHAR, CONVERT(INT, @ID) + 1)
			WHEN @ID >= 9 THEN 'HS00' + CONVERT(CHAR, CONVERT(INT, @ID) + 1)
		END
	RETURN @ID
END
GO

ALTER FUNCTION [dbo].[AUTO_MaNguoiDung]()
RETURNS VARCHAR(6)
AS
BEGIN
	DECLARE @ID VARCHAR(6)
	IF (SELECT COUNT(MaND) FROM NGUOIDUNG) = 0
		SET @ID = '0'
	ELSE
		SELECT @ID = MAX(RIGHT(MaND, 2)) FROM NGUOIDUNG
		SELECT @ID = CASE
			WHEN @ID >= 0 and @ID < 9 THEN 'ND000' + CONVERT(CHAR, CONVERT(INT, @ID) + 1)
			WHEN @ID >= 9 THEN 'ND00' + CONVERT(CHAR, CONVERT(INT, @ID) + 1)
		END
	RETURN @ID
END
GO

